export let InitialState = {
  authorizing: false,
  authorizationSuccessful: false,
  authorizationForm: {
    apiKey: '',
    email: '',
    siteUrl: '',
    error: false,
  },
  jiraIntegrationEnabled: false,
  authorizationLastTestedForm: {
    apiKey: '',
    email: '',
    siteUrl: '',
  },
  configurationForm: {
    allJiraProjectOptions: [],
    allJiraIssueTypeOptions: [],
    allJiraFieldMappingOptions: [],
    selectedJiraProject: {},
    selectedJiraIssueType: {},
    selectedJiraTitleFieldMapping: {},
    selectedJiraDetailsFieldMapping: {},
    selectedJiraLabels: [],
    selectedJiraEpic: {},
  },
  program: {},
  cesppaFields: [],
  jiraFields: [],
  jiraProjects: [],
  jiraProgram: {},
  issueType: '',
  selectedIssueType: {},
  selectedJiraProject: {},
  loading: false,
  programPublishedFindings: [],
  errorCreatingFindings: [],
}
