version: "3.5"

services:
  nginx:
    container_name: cesppa_nginx
    restart: always
    build:
      context: .
      args:
        - ENV_TAG=${ENV_TAG}
        - NGINX_CONFIG=${NGINX_CONFIG}
    ports:
      - "80:80"
      - "443:443"
    image: ${DOCKER_REGISTRY}/nginx:${TAG}
    env_file:
      - .env

  cypress:
    image: cypress/included:3.2.0
    container_name: cesppa_cypress
    working_dir: /e2e
    volumes:
      - ./cypress:/e2e
    env_file:
      - .env

volumes:
  node_modules:
