export const STORE_KEY = '$pendingTransactionSearch'

export const SEARCH_PENDING_TRANSACTIONS = 'SEARCH_PENDING_TRANSACTIONS'
export const SET_PENDING_TRANSACTIONS = 'SET_PENDING_TRANSACTIONS'
export const SET_PENDING_TRANSACTIONS_QUERY = 'SET_PENDING_TRANSACTIONS_QUERY'
