export const STORE_KEY = '$green-room'
export const LOAD_GREENROOM_VULNS = 'LOAD_GREENROOM_VULNS'
export const SET_GREENROOM_VULNS = 'SET_GREENROOM_VULNS'
export const GET_GREENROOM_VULNS = 'GET_GREENROOM_VULNS'
