export const STORE_KEY = '$signUp'

export const CHECK_CONFIRMATION = 'CHECK_CONFIRMATION'
export const CHECK_EMAIL = 'CHECK_EMAIL'
export const CHECK_USERNAME = 'CHECK_USERNAME'
export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT'
