name: main
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: download .env file from s3
        run: aws s3 cp --debug s3://cesppa-build-files/develop-k8/.env .env
      - name: Set TAG, ENV, and DOCKER_REGISTRY variables
        run: |
          echo "ENV_TAG=dev" >> .env
          echo "TAG=${{ github.sha }}" >> .env
          echo "TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "DOCKER_REGISTRY=720150013645.dkr.ecr.us-west-2.amazonaws.com" >> .env
      - name: Build containers
        run: docker-compose build
      - name: Push containers
        run: docker-compose push
      - name: Bump version in helm-charts
        uses: xlyk/tagliatelle-action@v2
        with:
          user: "inspectiv-service"
          token: "${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}"
          repo: "https://github.com/cesppa/helm-charts.git"
          file: "inspectiv/values-develop.yaml"
          tag: "${{ env.TAG }}"
          pattern: '(clientVersion: )(.*?)(\n)'
